name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # TAMBAHAN: Instal Node.js dan dependensi
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Gunakan versi Node yang stabil

      - name: Install dependencies
        run: npm install

      # Jalankan server lokal untuk aplikasi kita
      - name: Start local server
        run: npm start & # Tanda '&' menjalankan server di background

      # Instal & jalankan Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          wait-on: 'http://localhost:5500'